### ISSUE TITLE
Partes que no cargan en el headless

### ISSUE THREAD

**Issue by RodrigoZepeda** [RodrigoZepeda/CapacidadHospitalariaMX#15]
Usando chrome en headless como la más reciente actualización me arroja el siguiente error de que no puede encontrar el elemento. No sé si es algo mío por ahora voy a devolver el código a sin headless. 

```
Traceback (most recent call last):
  File "scripts/descarga_estatal.py", line 106, in <module>
    browser.find_element_by_xpath("/html/body/section/section[2]/div[2]/section/article[2]/article/div[1]/nav/ul/li[1]/a").click()
  File "/usr/local/Caskroom/miniconda/base/envs/capacidadhospitalaria/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/Caskroom/miniconda/base/envs/capacidadhospitalaria/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/Caskroom/miniconda/base/envs/capacidadhospitalaria/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/Caskroom/miniconda/base/envs/capacidadhospitalaria/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a href="estatal">...</a> is not clickable at point (369, 145). Other element would receive the click: <a data-source="resumen" data-scale="no-scale" class="secTab tabItem" href="resumen">...</a>
  (Session info: headless chrome=95.0.4638.69)
```

**Comment by florens21** [comment]
Hola, Rodrigo, sí,a mí me pasó lo mismo, es lo que te comenté una vez por mail cuando intenté hacer lo del Chrome headless. Sin embargo, lo que hice fue "tomar una foto" con el headless y así pude ver que lo que el navegador "veía" era diferente a lo que vemos en el modo normal, ya que la barra del encabezado de la página quedaba mucho más ancha, de forma que se tapaban los links para descargar los archivos en excel, csv o pdf, por eso no los encuentra.

Lo que hice y que me resolvió el problema fue probar con firefox headless en vez de Chrome.

Por cierto, ya logré lo que te había comentado que quería hacer de correr el código en la nube y que me descargue los archivos automáticamente directo en la nube, sin necesidad de que yo tenga que entrar para nada a mi computadora! 

Saludos.

**Comment by RodrigoZepeda** [comment]
Gracias y felicidades
